language: objective-c
before_script: git submodule update --init --recursive
script: xcodebuild -project 'BarrelApp/BarrelApp.xcodeproj' -sdk macosx10.10 -scheme BarrelApp build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
xcode_project: BarrelApp/BarrelApp.xcodeproj
xcode_scheme: BarrelApp
