language: objective-c
before_script: git submodule update --init --recursive
script: xcodebuild -project 'BarrelApp/BarellApp.xcodeproj' -sdk $SDK -scheme $SCHEME build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
xcode_project: BarrelApp/BarrelApp.xcodeproj
xcode_scheme: BarrelApp
