language: objective-c
before_script: git submodule update --init --recursive
script: xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO
xcode_project: BarrelApp/BarrelApp.xcodeproj
xcode_scheme: BarrelApp
